In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns

c:\Users\kongp\miniconda3\envs\tf\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
data = pd.read_csv("bank-additional.csv", header = 0, sep = ";")
data = data.dropna()

In [3]:
data.head()

age          job  marital          education default  housing     loan  \
0   30  blue-collar  married           basic.9y      no      yes       no   
1   39     services   single        high.school      no       no       no   
2   25     services  married        high.school      no      yes       no   
3   38     services  married           basic.9y      no  unknown  unknown   
4   47       admin.  married  university.degree      no      yes       no   

     contact month day_of_week  ...  campaign  pdays  previous     poutcome  \
0   cellular   may         fri  ...         2    999         0  nonexistent   
1  telephone   may         fri  ...         4    999         0  nonexistent   
2  telephone   jun         wed  ...         1    999         0  nonexistent   
3  telephone   jun         fri  ...         3    999         0  nonexistent   
4   cellular   nov         mon  ...         1    999         0  nonexistent   

  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0         -1.8          92.893          -46.2      1.313       5099.1  no  
1          1.1          93.994          -36.4      4.855       5191.0  no  
2          1.4          94.465          -41.8      4.962       5228.1  no  
3          1.4          94.465          -41.8      4.959       5228.1  no  
4         -0.1          93.200          -42.0      4.191       5195.8  no  

[5 rows x 21 columns]

In [4]:
data['education'].unique()

array(['basic.9y', 'high.school', 'university.degree',
       'professional.course', 'basic.6y', 'basic.4y', 'unknown',
       'illiterate'], dtype=object)

In [5]:
data['education'] = np.where(data['education'] == 'basic.9y', 'Basic', data['education'])
data['education'] = np.where(data['education'] == 'basic.4y', 'Basic', data['education'])
data['education'] = np.where(data['education'] == 'basic.6y', 'Basic', data['education'])

In [6]:
data['education'].unique()

array(['Basic', 'high.school', 'university.degree', 'professional.course',
       'unknown', 'illiterate'], dtype=object)

### Dummy Variable

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4119 entries, 0 to 4118
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             4119 non-null   int64  
 1   job             4119 non-null   object 
 2   marital         4119 non-null   object 
 3   education       4119 non-null   object 
 4   default         4119 non-null   object 
 5   housing         4119 non-null   object 
 6   loan            4119 non-null   object 
 7   contact         4119 non-null   object 
 8   month           4119 non-null   object 
 9   day_of_week     4119 non-null   object 
 10  duration        4119 non-null   int64  
 11  campaign        4119 non-null   int64  
 12  pdays           4119 non-null   int64  
 13  previous        4119 non-null   int64  
 14  poutcome        4119 non-null   object 
 15  emp.var.rate    4119 non-null   float64
 16  cons.price.idx  4119 non-null   float64
 17  cons.conf.idx   4119 non-null   f

In [8]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [9]:
cat_vars = ['job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'poutcome',]

for var in cat_vars:
    cat_list = 'var' + '_' + var
    cat_list = pd.get_dummies(data[var], prefix = var)
    data1 = data.join(cat_list)
    data = data1

In [10]:
cat_vars = ['job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'poutcome',]

data_vars = data.columns.values.tolist()

In [11]:
to_keep = [i for i in data_vars if i not in cat_vars]

In [12]:
data_final = data[to_keep]
data_final.columns.values

array(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired',
       'job_self-employed', 'job_services', 'job_student',
       'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_Basic', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown', 'default_no',
       'default_unknown', 'default_yes', 'housing_no', 'housing_unknown',
       'housing_yes', 'loan_no', 'loan_unknown', 'loan_yes',
       'contact_cellular', 'contact_telephone', 'month_apr', 'month_aug',
       'month_dec', 'month_jul', 'month_jun', 'month_mar', 'month_may',
       'month_nov', 'month_oct', 'month_sep', 'day_of_week_fri',

### SMOTE

In [13]:
X = data_final.loc[:, data_final.columns != 'y']
y = data_final.loc[:, data_final.columns == 'y']

from imblearn.over_sampling import SMOTE

In [14]:
os = SMOTE(random_state = 1234)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1234)
columns = X_train.columns

In [15]:
os_data_X, os_data_y = os.fit_resample(X_train, y_train)
os_data_X = pd.DataFrame(data = os_data_X, columns = columns)
os_data_y = pd.DataFrame(data = os_data_y, columns = ['y'])

In [16]:
os_data_X

age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0      49       139         1    999         0      1.100000       93.994000   
1      38        19        11    999         0      1.400000       93.444000   
2      36       360         2    999         0      1.100000       93.994000   
3      57       322         2    999         0     -1.800000       93.075000   
4      28       402         1    999         0     -1.800000       92.893000   
...   ...       ...       ...    ...       ...           ...             ...   
5121   50       705         6    999         0      1.400000       94.465000   
5122   38       428         1    999         0     -2.947350       92.839800   
5123   34       270         1      9         1     -2.106500       93.654238   
5124   42       473         1      3         2     -2.409912       93.467861   
5125   64       522         1     19         1     -1.945504       93.303523   

      cons.conf.idx  euribor3m  nr.employed  ...  month_oct  month_sep  \
0        -36.400000   4.858000  5191.000000  ...      False      False   
1        -36.100000   4.965000  5228.100000  ...      False      False   
2        -36.400000   4.859000  5191.000000  ...      False      False   
3        -47.100000   1.405000  5099.100000  ...      False      False   
4        -46.200000   1.327000  5099.100000  ...      False      False   
...             ...        ...          ...  ...        ...        ...   
5121     -41.800000   4.959000  5228.100000  ...      False      False   
5122     -30.606072   0.714059  5015.010425  ...       True      False   
5123     -37.408821   0.772021  4997.793154  ...      False       True   
5124     -35.749324   0.717494  5002.415722  ...      False      False   
5125     -34.372581   0.660365  5009.500274  ...      False      False   

      day_of_week_fri  day_of_week_mon  day_of_week_thu  day_of_week_tue  \
0               False            False            False            False   
1               False            False            False             True   
2               False            False            False            False   
3               False             True            False            False   
4               False            False             True            False   
...               ...              ...              ...              ...   
5121             True            False            False            False   
5122             True            False             True            False   
5123            False            False            False             True   
5124             True             True            False            False   
5125             True            False            False             True   

      day_of_week_wed  poutcome_failure  poutcome_nonexistent  \
0                True             False                  True   
1               False             False                  True   
2                True             False                  True   
3               False             False                  True   
4               False             False                  True   
...               ...               ...                   ...   
5121             True             False                  True   
5122            False              True                  True   
5123             True             False                 False   
5124            False             False                 False   
5125            False              True                 False   

      poutcome_success  
0                False  
1                False  
2                False  
3                False  
4                False  
...                ...  
5121             False  
5122             False  
5123              True  
5124              True  
5125              True  

[5126 rows x 61 columns]

In [17]:
X_train.shape

(2883, 61)

In [18]:
os_data_X.shape

(5126, 61)

### RFE - Recursive Feature Elimination

In [20]:
data_final_vars = data_final.columns.values.tolist()
y = ['y']
X = [i for i in data_final_vars if i not in y]

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [21]:
logreg = LogisticRegression(solver='lbfgs', max_iter=100000)

In [22]:
rfe = RFE(estimator=logreg, n_features_to_select=20)
rfe = rfe.fit(os_data_X, os_data_y.values.ravel())

c:\Users\kongp\miniconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [23]:
rfe.support_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True, False,  True,
        True, False,  True,  True,  True, False, False, False,  True,
        True,  True, False, False, False,  True,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
        True,  True,  True,  True, False, False,  True])

In [24]:
rfe.ranking_

array([37, 39, 34, 40, 31, 33, 32, 35, 30, 38, 10, 13, 17, 12, 16,  7, 14,
       11,  6,  9,  8, 15,  1,  1,  1, 36,  1,  1, 42,  1,  1,  1, 19, 20,
       41,  1,  1,  1,  4,  3,  5,  1,  1, 23, 26,  2, 25, 22,  1, 24, 27,
       18, 21,  1,  1,  1,  1,  1, 28, 29,  1])

In [25]:
data_final.columns

Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_Basic', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown', 'default_no',
       'default_unknown', 'default_yes', 'housing_no', 'housing_unknown',
       'housing_yes', 'loan_no', 'loan_unknown', 'loan_yes',
       'contact_cellular', 'contact_telephone', 'month_apr', 'month_aug',
       'month_dec', 'month_jul', 'month_jun', 'month_mar', 'month_may',
       'month_nov', 'month_oct', 'month_sep', 'day_of_week_fri',
      

In [26]:
len(rfe.ranking_)

61

In [28]:
columns_name = []

for i in range (len(rfe.ranking_)):
    if rfe.ranking_[i] == 1:
        columns_name.append(data_final.columns[i])

In [29]:
columns_name

['job_unknown',
 'marital_divorced',
 'marital_married',
 'marital_unknown',
 'education_Basic',
 'education_illiterate',
 'education_professional.course',
 'education_university.degree',
 'default_yes',
 'housing_no',
 'housing_unknown',
 'loan_yes',
 'contact_cellular',
 'month_jun',
 'month_sep',
 'day_of_week_fri',
 'day_of_week_mon',
 'day_of_week_thu',
 'day_of_week_tue',
 'poutcome_nonexistent']

In [30]:
X = os_data_X[columns_name]
y =os_data_y['y']

In [31]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression()

In [32]:
y_pred = logreg.predict(X_test)
print(logreg.score(X_test, y_test))


0.8302990897269181


In [33]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[653 126]
 [135 624]]
